#!/usr/bin/env bash

cd "$(dirname "`readlink -f "$0"`")"
export link="$(pwd)"
cd "${link}/../../"
export WINE_PATH="$(pwd)"

"${WINE_PATH}/data/utils/sw_runtime" "${WINE_PATH}/data/scripts/start.sh" "$@"
